# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16714NVzFKZKuksWsEDpu2j7Bf63O8LIH
"""

from flask import Flask, request, jsonify
import sqlite3
from cryptography.fernet import Fernet
from flask_bcrypt import Bcrypt

app = Flask(__name__)
bcrypt = Bcrypt(app)

db_path = "password_manager.db"

# Load encryption key
with open("secret.key", "rb") as f:
    key = f.read()

cipher = Fernet(key)


@app.route("/")
def home():
    return "Password Manager API is running"


# REGISTER
@app.route("/register", methods=["POST"])
def register():

    data = request.json

    username = data["username"]
    email = data["email"]
    password = data["password"]

    password_hash = bcrypt.generate_password_hash(
        password
    ).decode("utf-8")

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("""
    INSERT INTO users
    (username, email, password_hash)
    VALUES (?, ?, ?)
    """, (
        username,
        email,
        password_hash
    ))

    conn.commit()
    conn.close()

    return jsonify({
        "message": "User registered"
    })


# LOGIN
@app.route("/login", methods=["POST"])
def login():

    data = request.json

    email = data["email"]
    password = data["password"]

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("""
    SELECT id, password_hash
    FROM users
    WHERE email = ?
    """, (email,))

    result = cursor.fetchone()

    conn.close()

    if result is None:
        return jsonify({
            "message": "User not found"
        })

    user_id = result[0]
    stored_hash = result[1]

    if bcrypt.check_password_hash(
        stored_hash,
        password
    ):
        return jsonify({
            "message": "Login successful",
            "user_id": user_id
        })

    else:
        return jsonify({
            "message": "Invalid password"
        })


# VIEW PASSWORDS
@app.route("/passwords/<int:user_id>")
def view_passwords(user_id):

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("""
    SELECT website,
           account_username,
           encrypted_password
    FROM passwords
    WHERE user_id = ?
    """, (user_id,))

    rows = cursor.fetchall()

    conn.close()

    data = []

    for row in rows:

        decrypted = cipher.decrypt(
            row[2]
        ).decode()

        data.append({
            "website": row[0],
            "username": row[1],
            "password": decrypted
        })

    return jsonify(data)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)